#!/bin/bash
export MOZ_DISABLE_CONTENT_SANDBOX=1

# set -o xtrace

if [ -z "$1" ]; then 
	echo "Expected argument ./runPerfTest output_folder [platform=32|64]"; 
	exit 1; 
fi

if [[ -f "$1" ]]; then
	echo "$1 already exists"; 
	exit 1; 
fi

OUTPUTPATH=$(cd "$(dirname "$1")"; pwd)/$(basename "$1")
mkdir -p ${OUTPUTPATH}
cd "$(dirname "$0")"
Pl="64"

if [[ ! -z "$4" ]]; then
	if [[ "$4" == "32" ]]; then
		Pl="32"
	else
		echo "Unknown platform: $4"
		exit 1
	fi
fi

# FFVersionsDir=("../mozilla_firefox_stock/" "./" "./" "./" "./" "./")
# FFVersionsSuffix=("_stock" "" "" "" "" "")
# FFVersions=("static" "static_buffcopy" "nacl" "new_nacl_cpp" "new_ps_cpp" "new_ps_cpp_mutex")
# #Process sbx is pinned to core 3. process-spin firefox is on separate core --- core 1, while process mutex is on the same core 3
# FFPinCores=("1" "1" "1" "1" "1" "3")

FFVersionsDir=("./" "./" "../mozilla_firefox_stock/")
FFVersionsSuffix=("" "" "_stock")
FFVersions=("new_nacl_cpp" "new_ps_cpp" "static")
FFPinCores=("1,3" "1" "1,3")

# FFVersionsDir=("./")
# FFVersionsSuffix=("")
# FFVersions=("new_ps_cpp_mutex")
# FFPinCores=("3")

#FFVersionsDir=("../mozilla_firefox_stock/")
#FFVersionsSuffix=("_stock")
#FFVersions=("static")
#FFPinCores=("1")

if [ ${#FFVersionsDir[@]} -ne ${#FFVersions[@]} ]; then
	echo "Versions Dir and Versions do not match";
	exit 1;
fi

if [ ${#FFVersionsSuffix[@]} -ne ${#FFVersions[@]} ]; then
	echo "Versions Suffix and Versions do not match";
	exit 1;
fi

if [ ${#FFPinCores[@]} -ne ${#FFVersions[@]} ]; then
	echo "Pin Cores and Versions do not match";
	exit 1;
fi

for (( i = 0; i < ${#FFVersions[@]}; i++ )); do 
	if [[ ! -d "../ffbuilds/firefox_${Pl}bit_optdebug_${FFVersions[$i]}" ]]; then
		echo "Not all firefox versions found: ../ffbuilds/firefox_${Pl}bit_optdebug_${FFVersions[$i]}";
		exit 1;
	fi
done

echo "Starting. Make sure to "
echo "1. Disable scaling first with. sudo cpufreq-set -c 3 --min 2200MHz --max 2200MHz"
echo "2. Run the zlib testing server with node server.js"


# param: outputDir/prefix
# param: cores
function runTest(){
	rm -f ./testing/mozharness/build/local.json
	#sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
	sleep 2

	taskset -c $2 ./mach talos-test --suite rlbox_test 2>&1 | tee "$1_terminal_output.txt"
	retVal=${PIPESTATUS[0]}
	if [ $retVal -ne 0 ]; then
		exit 1
	fi
	sleep 2
	mv ./testing/mozharness/build/local.json "$1_rlbox_test_page_render.json"

	# taskset -c $2 ./mach talos-test --suite rlbox_scaling 2>&1 | tee "$1_scaling_terminal_output.txt"
	# retVal=${PIPESTATUS[0]}
	# if [ $retVal -ne 0 ]; then
	# 	exit 1
	# fi
	# sleep 2
	# mv ./testing/mozharness/build/local.json "$1_rlbox_scaling_page_render.json"

	# taskset -c $2 ./mach talos-test --suite extern_page_load_test_ten 2>&1 | tee "$1_externalpage_output.txt"
	# retVal=${PIPESTATUS[0]}
	# if [ $retVal -ne 0 ]; then
	# 	exit 1
	# fi
	# sleep 2
	# mv ./testing/mozharness/build/local.json "$1_external_page_render.json"

	# taskset -c $2 ./mach talos-test --activeTests extern_page_load11 2>&1 | tee "$1_externalpage_output.txt"
	# retVal=${PIPESTATUS[0]}
	# if [ $retVal -ne 0 ]; then
	# 	exit 1
	# fi
	# sleep 2
	# mv ./testing/mozharness/build/local.json "$1_external_page_render11.json"

	# taskset -c $2 ./mach talos-test --activeTests png_perf 2>&1 | tee "$1_terminal_output.txt"
}

SAVEDDIR=$PWD

for (( j = 0; j < ${#FFVersions[@]}; j++ )); do 
	cd ${FFVersionsDir[$j]}
	cp "mozconfig${Pl}_${FFVersions[$j]}" mozconfig
	pkill -f ProcessSandbox_otherside
	pkill -f WebContent
	pkill -f firefox
	runTest "${OUTPUTPATH}/${FFVersions[$j]}${FFVersionsSuffix[$j]}" "${FFPinCores[$j]}"
	cd $SAVEDDIR
done

sleep 2

for (( j = 0; j < ${#FFVersions[@]}; j++ )); do 
	./newAnalyzePerf.py "${OUTPUTPATH}/${FFVersions[$j]}${FFVersionsSuffix[$j]}_terminal_output.txt" 2>&1 >> "${OUTPUTPATH}/${FFVersions[$j]}${FFVersionsSuffix[$j]}_terminal_analysis.json"
	# ./newAnalyzePerf.py "${OUTPUTPATH}/${FFVersions[$j]}${FFVersionsSuffix[$j]}_scaling_terminal_output.txt" 2>&1 >> "${OUTPUTPATH}/${FFVersions[$j]}${FFVersionsSuffix[$j]}_scaling_terminal_analysis.json" True
done
